### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FLAG_MAP'

### ISSUE THREAD

**Issue by wiemp** [inexio/snmpsim#12]
Executing 
`snmpsim-command-responder --data-dir=./data --agent-udpv4-endpoint=127.0.0.1:1024`

results in 

`Traceback (most recent call last):
  File "/bin/snmpsim-command-responder", line 9, in <module>
    load_entry_point('thola-snmpsim==1.0.0', 'console_scripts', 'snmpsim-command-responder')()
  File "/usr/lib/python2.7/site-packages/thola_snmpsim-1.0.0-py2.7.egg/snmpsim/commands/responder.py", line 236, in main
    '--debug-asn1', choices=pyasn1_debug.FLAG_MAP,
AttributeError: 'module' object has no attribute 'FLAG_MAP'`

Suggested fix:
_snmpsim/commands/responder.py:236_

       ` '--debug-asn1', choices=pyasn1_debug.FLAG_MAP,`

to

        `'--debug-asn1', choices=pyasn1_debug.flagMap,`

**Comment by wiemp** [comment]
Might be related to python version 2.7 and the installed pyasn1-0.4.2-py2.7. Doesn't occur with  pyasn1-0.4.8-py2.py3.
